<?php
$liste_3mic = array(
'--',
'Afonso Perrine',
'Ahamdy Jdihadi',
'Al Ajroudi Alexandre',
'Alaverdov Antoine',
'Amari Youssef',
'Amegouz Zineb',
'Arfa Amine',
'Arrondelle Hugo',
'Aubut Guillaume',
'Bacconnier Agathe',
'Bah Thierno Amadou',
'Ballotin Thomas',
'Barbanson Adrien',
'Barnabe Elise',
'Baudoint Emma',
'Belay Nahom',
'Benassai Marino',
'Benazzouz Abir',
'Benchehida Yacine',
'Bensiali Adrien',
'Bonneau Clementine',
'Bouisson Arnaud',
'Cadot Benjamin',
'Calmettes Pierre',
'Cavailles Kevin',
'Chabloz Ellias',
'Chaine Clement',
'Cotte Thomas',
'Dechambe Mathieu',
'Decore Jerome',
'Dubois Aubry',
'Dumaz Clement',
'Ebersohl Gwenael',
'Faure Paul',
'Fontana Theo',
'Foussats Morgane',
'Fragonas Fabrice',
'Gallois Leonie',
'Giraud Theau',
'Gonzalvez Alexandre',
'Guerbette Valentin',
'Gues Marianne',
'Hihi Issam',
'Hok Jean-Remy',
'Hou Yunan',
'Jacques Matthieu',
'Karaoud Rami',
'Labourdette Titouan',
'Lartigue Auriane',
'Lau  Dany',
'Laur Pierre',
'Le Belguet Hugo',
'Leon Florian',
'Luque Terani',
'Mahjoubi Ayoub',
'Makri Rayane',
'Moenne-Loccoz Celestin',
'Moine Robin',
'Molina Damien',
'Moukhlis Nabil',
'Noblet Gabin',
'Pavlova Alexandra',
'Picco Bastien',
'Poncetta Thibault',
'Rafik Sana',
'Rouby Nathan',
'Rouzot Julien',
'Sanchez Jean-Christophe',
'Schafer Susanna',
'Shi Mengxia',
'Simard Yohan',
'Smaniotto Nathan',
'Soumare Coumba',
'Tali Elies',
'Thebault Paul',
'Tragin Valentin',
'Vergnet Arnaud',
'Vincent Guillaume',
'Wadsten Anna',
'Wang Yifan',
'Yang Yuyuan',
'Zakharov Mikhail' );
?>