<?php
$liste_3imacs = array(
'--',
'Aissaoui Mohammed Tayeb',
'Aymonnier Tom',
'Baghdadi Mohammed Zakaria',
'Berton Thomas',
'Boukezzata Aymen',
'Brisset Odran',
'Burton Nidishlall',
'Cavailles Paul',
'Choulot Romain',
'Collobert Alexandre',
'Cruz Sarah',
'Delcourt Matis',
'Diallo Youssouf',
'Didier Clement',
'Doly Joffrey',
'Doutriaux Eliott',
'Dumas-Grollier Solene',
'Marina Edinso',
'Edouaa Mohamed',
'El Hachimi Asmae',
'El Hammoumi El Mehdi',
'El Khamlichi Imane',
'Faye Serigne',
'Fercoq Nicolas',
'Frances Marcos',
'Frouin Mathis',
'Gilbert Valentin',
'Giusti Laura',
'Gueye Alassane',
'Ibled Mathilde',
'Jorge Axel',
'Khattabi Badr',
'Laffargue Lenny',
'Laxague Lea',
'Le Quang Phu',
'Leconte Tanguy',
'Lerat Baptiste',
'Lievre Agathe',
'Liu Yixia',
'Mackay Ewan',
'Maier Amelie',
'Manzo Yiannis',
'Martin Gautier',
'Mbaye Cheikh',
'Meyer Carole',
'Mikhin Nikita',
'Mochalov Ilia',
'Muon Duc Minh',
'Nembrini-Moral Tino',
'Nguyen Assia',
'Nougue Paul',
'Nouguerede Louis',
'Pannetier Marvyn',
'Pianazza Lucie',
'Piqueras Valentin',
'Piques Nicolas',
'Pitault Lea',
'Quintana Y Arciosana Beranger',
'Ramiara Maxime',
'Riman Chams',
'Rio Raphael',
'Rongere Celestin',
'Sable William',
'Tami Theo',
'Tatger Corentin',
'Taulan Lucas',
'Touchais Julien',
'Tremoulet Sarah',
'Urben Baptiste',
'Zakaghia Souhail',
'Zappa Arthur',
'Zelani Quentin',
'Zhang Liao' );
?>
